from building import *

cwd     = GetCurrentDir()

src = Split('''
main.c
bd_speech_rcg.c
cn_font.c
cn_port.c
mycc936.c
''')

CPPPATH = [str(Dir('#')), cwd]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
